[package]
name = "sprs-tests"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2018"
publish = false
rust-version.workspace = true

[dev-dependencies]
sprs = { path = "../sprs", features = ["serde"], default-features = false }
serde_json = "1.0.58"
